#+hugo_base_dir: ../
#+hugo_section: /
#+hugo_level_offset: 1
* Título de headline orgmode home
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:END:
Se supone que el contenido de la página principal aquí se escribe
* 
#+html: <div class="mio">
* Cotización Revisada de Ampliación Panel Solar - Rodolfo Alanís
:PROPERTIES:
:EXPORT_FILE_NAME: rodolfo-alanis2
:EXPORT_HUGO_SECTION: cotiza
:END:
** Cotización Ampliación Paneles para Rodolfo Alanís
*** Datos sobre esta cotización
- Para :: Rodolfo Alanís V.
- Fecha :: <2019-11-20 mié>
- Dirección :: Portón 514, Col. Portón del Valle Alto Mty NL 67277

*** Descripción del requerimiento
Cotizar dos opciones:
- 4 módulos fotovoltaicos dejando preparación para después ampliar a 8 con micro-inversor.
- 8 módulos fotovoltaicos adicionales de 405w con financiamiento.

*** Propuestas
Dos propuestas con mejoras opcionales. Ambas de 10 módulos fotovoltaicos de calidad Tier 1 (certificación que otorga Bloomberg Finnancial a proveedores confiables para créditos bancarios en proyectos internacionales).

#+html: <div class="columnas"><div class="junto">

**** Propuesta 1

#+attr_html: :class bold-ultima-linea moneda-1 moneda-2
#+caption: 4 Módulos de 330w
| PRECIO PANEL SOLAR   | USD*     | MXP       |
| Panel Solar Completo | 2,031.71 | 39,516.67 |
| Instalación          |          | 9,599.37  |
| S. Monitoreo         |          | 4,853.06  |
| Total Panel SolarCFE |          | 53,969    |


Material importado a tipo de cambio de $19.45 ±20 centavos.

*Tipo de Inversor en esta propuesta:*

Micro-inversor con sistema de monitoreo. 


#+html: </div><div class="junto">

**** Propuesta 2

#+attr_html: :class bold-ultima-linea moneda-1 moneda-2
#+caption: 8 módulos de 405 watts
| PRECIO PANEL SOLAR    | USD      | MXP       |
| Panel Solar Completo  | 3,563.55 | 69,311.09 |
| Instalación           |          | 16,106.42 |
| S. Monitoreo          |          | 1,128.57  |
| SubTotal  Panel Solar |          | 86,546.08 |


Material importado en usd a tipo de cambio de $19.45 ±20 centavos.

*Tipo de Inversor en esta propuesta:*

Inversor estándar (Chino - equivalente a 5 años de garantía).

*Mejoras opcionales:*

Como mejora opcional, sería poner inversor alemán de 10 años de garantía por costo adicional de $11,698 mxp.

#+html: </div></div>

*** Condiciones Comerciales
#+html: <div class="columnas"><div class="junto">

**** Tipo de cambio
- El precio es en pesos para esta cotización y queda establecido en base al precio en el Diario Oficial de la Federación el día de pago del anticipo.
- Si el tipo de cambio sufre un aumento o disminución mayor de 20 centavos, el precio total de proyecto se ajustará.

**** Forma de pago
- Los pagos se hacen en efectivo o por cheque.
- Anticipo del 50% al inicio del proyecto al tiempo de la firma del contrato.
- 20% adicional contra entrega del proyecto del proyecto instalado, funcionando.
- 2x15% pagos mensuales (Enero y Febrero 2020).

**** Tiempos de entrega
- La entrega del equipo fotovoltáico tarda ocho días hábiles a partir de la entrega de anticipo y firma de contrato compra-venta.
- La instalación de panel solar, tarda dos semanas a partir de la entrega de los materiales.

#+html: </div><div class="junto">

**** Sobre garantías
- Los componentes que se entregan son nuevos y cuentan con la garantía de fábrica propia de cada componentes.
- Al final del proyecto se hace entrega de la documentación de cada componente.
- El panel solar cuenta con 10 años de garantía en defectos de fabricación y 25 años garantía de producción mínima del 80%.
- La estructura de soporte de aluminio cuenta con una garantía del fabricante de 20 años.
- La mano de obra está garantizada por 5 años, esto es que calidad de la instalación cumpla con las normas vigentes.

**** Garantía extendida incluida
- *Como cobertura de garantía extendida por dos años:* Queda cubierto adicionalmente que cualquier falla en los componentes, según se detecte en el sistema de monitoreo, será inspeccionado y corregido sin costo de mano de obra.
- Posteriormente, los componentes principales continúan con su garantía original de fábrica y el usuario es responsable de reportar y conseguir hacer efectiva la garantía directo con el fabricante en caso necesario, así como la contratación de la mano de obra del trabajo de reparación.
- Opcional se ofrecerán contratos para ampliar la cobertura de garantía extendida y mantenimiento,  por un costo aproximado $250/módulo fotovoltaico (por definir).

#+html: </div></div>
* Prueba si funciona elm
:PROPERTIES:
:EXPORT_FILE_NAME: pagina-con-elm
:EXPORT_HUGO_SECTION: pruebas
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :elm "SpecialElmApp" :subtitle "Probando Apicaciones con Elm"
:END:
#+HTML: <div id="myapp"></div>
